version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mglFuture7@$
      MYSQL_USER: admin
      MYSQL_PASSWORD: mglFuture7@$
      MYSQL_DATABASE: mgldefi
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: